### PR TITLE
GFM Parser prototype

### LINKED ISSUE #6: GFM to AST Parser Prototype
## Building a working Markdown (gfm) to AST parser prototype (Week II)
General issue for managing Week II and associated tasks related with the parser.
Resources:

- [AST documentation](https://github.com/ZPRP24Z/pyndoc/wiki/AST)
- Related PR - #8

### PR DESCRIPTION
**Pull request by doaads**
Basic prototype of the gfm parser.
EDIT:
The reader/parser will rely less on regular expressions and instead of parsing the whole document at once, the parsing will be done per-character

#6

### CODE REVIEW

**Comment by doaads** [comment]
~TODO:~
~- [x] Fix naming (GFM blocks should just be generic blocks, there is no differentiation between block types for each language, only the logic)~

**Comment by doaads** [comment]
## Major change
The whole parser/reader is being redone from scratch with a hopefully more robust solution, relying less on regex, and more on parsing tokens

**Comment by doaads** [comment]
Basic parser is in working condition, tests are provided, new block additions will be made in subsequent PRs

**Review by sucholbluk — APPROVED** [review]
Fine for now. We will need to add reading Para blocks asap.

**Pull request merged**
